# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 771, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textEdit_filename = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_filename.sizePolicy().hasHeightForWidth())
        self.textEdit_filename.setSizePolicy(sizePolicy)
        self.textEdit_filename.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_filename.setObjectName("textEdit_filename")
        self.horizontalLayout.addWidget(self.textEdit_filename)
        self.pushButton_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_browse.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.horizontalLayout.addWidget(self.pushButton_browse)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 640, 771, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_StartCapture = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_StartCapture.setObjectName("pushButton_StartCapture")
        self.horizontalLayout_2.addWidget(self.pushButton_StartCapture)
        self.pushButton_StopCapture = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_StopCapture.setObjectName("pushButton_StopCapture")
        self.horizontalLayout_2.addWidget(self.pushButton_StopCapture)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 481, 40))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 130, 771, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 50, 351, 10))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 570, 771, 67))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_glasses = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_glasses.setObjectName("checkBox_glasses")
        self.horizontalLayout_3.addWidget(self.checkBox_glasses)
        self.checkBox_cigarette = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_cigarette.setObjectName("checkBox_cigarette")
        self.horizontalLayout_3.addWidget(self.checkBox_cigarette)
        self.checkBox_n95mask = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_n95mask.setObjectName("checkBox_n95mask")
        self.horizontalLayout_3.addWidget(self.checkBox_n95mask)
        self.checkBox_fps = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_fps.setObjectName("checkBox_fps")
        self.horizontalLayout_3.addWidget(self.checkBox_fps)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.menu_File.addAction(self.action_Exit)
        self.menu_About.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Model filename:"))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse"))
        self.pushButton_StartCapture.setText(_translate("MainWindow", "Start Capture"))
        self.pushButton_StopCapture.setText(_translate("MainWindow", "Stop Capture"))
        self.label_2.setText(_translate("MainWindow", "W207 - Project4: Facial KeyPoint Detection"))
        self.label_3.setText(_translate("MainWindow", "By Dr. Tensorflow: Julia Ying, Haerang Lee, Sang Lee"))
        self.groupBox.setTitle(_translate("MainWindow", "Fashion Items"))
        self.checkBox_glasses.setText(_translate("MainWindow", "Glasses"))
        self.checkBox_cigarette.setText(_translate("MainWindow", "Cigarette"))
        self.checkBox_n95mask.setText(_translate("MainWindow", "N95 Mask"))
        self.checkBox_fps.setText(_translate("MainWindow", "Facial Points"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_About.setTitle(_translate("MainWindow", "&About"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_About.setText(_translate("MainWindow", "&About"))
